#PBS -N cellranger_PF_6
#PBS -A GT-ggibson3-biocluster
#PBS -l nodes=1:ppn=10
#PBS -l pmem=22gb
#PBS -l walltime=36:00:00
#PBS -o cellranger_PF_6.out
#PBS -m abe
#PBS -M naughtoncolin@gatech.edu

cd $PBS_O_WORKDIR

# cellranger count
/storage/home/hcoda1/0/cnaughton7/p-ggibson3-0/software/cellranger-6.1.2/cellranger count \
--id=PA_6 \
--fastqs=/storage/home/hcoda1/0/cnaughton7/p-ggibson3-0/Emory/PA6fastqs \
--transcriptome=/storage/home/hcoda1/0/cnaughton7/p-ggibson3-0/software/refdata-gex-GRCh38-2020-A